#!/usr/bin/env python
# Copyright (c) 2010 Pablo Seminario <pabluk@gmail.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import logging
from optparse import OptionParser
import pygtk
pygtk.require('2.0')
import gtk
import gettext
import locale

locale.setlocale(locale.LC_ALL, '')
gettext.install('screenkey', unicode=True)

from Screenkey import APP_NAME, APP_DESC, VERSION
from Screenkey.screenkey import Screenkey

gtk.gdk.threads_init()

def Main():
    parser = OptionParser(description=APP_DESC, version=VERSION)
    parser.add_option("--no-detach", action="store_true", 
        dest="nodetach", default=False, 
        help=_("do not detach from the parent"))
    parser.add_option("-d", "--debug", action="store_true",
        dest="debug", default=False, help=_("show debug information"))
    parser.add_option("-t", "--timeout", type="int", dest="timeout",
        help=_("timeout"), default=2)
    parser.add_option("-s", "--size", type="int", dest="size",
        help=_("size"), default=4)
    parser.add_option("-m", "--mode", type="int", dest="mode",
        help=_("mode"), default=1)
    parser.add_option("-p", "--position", type="int", dest="position",
        help=_("position"), default=2)
    parser.add_option("-o", "--opacity", type="float", dest="opacity",
        help=_("opacity"), default=0.7)
    parser.add_option("-b", "--bgcolor", type="string", dest="bgcolor",
        help=_("bgcolor"), default='black')
    parser.add_option("-f", "--font", type="string", dest="font",
        help=_("font"), default='Sans')
    #parser.add_option("-c", "--color", type="string",
        #dest="color", help=_("color"), default='TODO')
    (options, args) = parser.parse_args()

    if options.debug:
        if options.nodetach:
            # Send debug messages to standard output
            logfile = None
        else:
            logfile = os.path.join(os.path.expanduser('~'), 
                                   '.screenkey.log')
            username = os.environ.get('SUDO_USER')
            if username:
                homedir = os.path.expanduser('~%s' % username)
                if homedir != '~%s' % username:
                    logfile = os.path.join(homedir, '.screenkey.log')
        logging.basicConfig(filename=logfile, level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(APP_NAME)

    s = Screenkey(logger=logger, nodetach=options.nodetach,
            timeout=options.timeout,
            size=options.size,
            mode=options.mode,
            position=options.position,
            opacity=options.opacity,
            bgcolor=options.bgcolor,
            font=options.font#,
            #color=options.color)
            )
    gtk.main()


if __name__ == "__main__":
    Main()

