#!/bin/bash

if [ $# -lt 2 ]
then
    if [ $# = 1 ] && [ "$1" = "-h" ]
    then
        echo "This is help"
        exit 1
    fi
    echo "Incorrect number of arguments. At least 2 arguments required."
    echo "Usage: $0 [WINNAME] [DURATION] [...ARGS]"
    exit 1
fi

win="$1"
shift
duration="$1"
shift

OPTIND=1
unknownargs=0

outfile='out.gif'

while getopts ":Fo:" opt; do
    case "${opt}" in
        F)
            force=force
            ;;
        o)
            outfile=${OPTARG}
            ;;
        *)
            unknownargs=$((unknownargs+1))
            ;;
    esac
done

shift $((OPTIND-1-unknownargs))

if [ -f "$outfile" ] && [ -z "$force" ]
then
    echo "Warning: $outfile already exists."
    read -p "Continue? [y/n] " yn
    case $yn in
        [Yy]*)
            ;;
        *)
            exit
            ;;
    esac
fi

# get screen dimensions
IFS='x' read sw sh < <(xdpyinfo | grep dimensions | awk '{print $2}')
# get window geometry
read wx wy ww wh < <(wmctrl -lG | grep $win | sed 's/^[^ ]* *[^ ]* //;s/[^0-9 ].*//;')
# compute and set new coordinates
wx=$(($sw/2-$ww/2))
wy=$(($sh-$wh))
wmctrl -r $win -e 0,$wx,$wy,$ww,$wh

(
# start screenkey
"$(dirname "$(readlink -f "$0")")/screenkey/screenkey" $@ >/dev/null 2>&1

if [[ $duration == W* ]]
then
    ENDCMD="--exec \"bash -c 'while kill -0 ${duration:1}; do :; done'\" "
else
    ENDCMD="-d ${duration}"
fi

# start recording the window
byzanz-record -x $wx -y $wy -w $ww -h $wh $ENDCMD "$outfile" 2> /dev/null

# finished
ps ax | grep 'screenkey' | grep -o '^[0-9 ]*' | head -n1 | xargs kill
) &
